events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://react_app;  # Forward to React app
    }

    location /api/ {
      proxy_pass http://backend:5001;  # Forward to backend
    }
  }
}